export {
  colors,
  gradients,
  glass,
  shadows,
  typography,
  radii,
  spacing,
  halos,
  transitions,
  zIndex,
  layout,
  fontFamilies,
  textStyles,
  componentStyles,
  routePattern,
  theme,
  type Theme,
  type Colors,
  type Gradients,
  type Glass,
  type Shadows,
  type Typography,
  type Radii,
  type Spacing,
  type Halos,
  type Transitions,
  type ZIndex,
  type Layout,
  type FontFamilies,
  type TextStyles,
  type ComponentStyles,
} from './tokens';

// Backward compatibility exports for existing imports
export const fonts = {
  heading: 'PlayfairDisplay',
  headingBold: 'PlayfairDisplay_700Bold',
  body: 'Inter_400Regular',
  bodyMedium: 'Inter_500Medium',
  bodySemiBold: 'Inter_600SemiBold',
  bodyBold: 'Inter_700Bold',
  display: 'Poppins_600SemiBold',
  displayBold: 'Poppins_700Bold',
  displayExtraBold: 'Poppins_800ExtraBold',
} as const;

export { colors as oldColors, brand, dark, radii as oldRadii, shadows as oldShadows, spacing as oldSpacing, gradients as oldGradients, play } from './tokens';