export {
  glass,
  halos,
  transitions,
  zIndex,
  layout,
  fontFamilies,
  textStyles,
  componentStyles,
  routePattern,
  theme,
  type Theme,
  type Colors,
  type Gradients,
  type Glass,
  type Shadows,
  type Typography,
  type Radii,
  type Spacing,
  type Halos,
  type Transitions,
  type ZIndex,
  type Layout,
  type FontFamilies,
  type TextStyles,
  type ComponentStyles,
} from './tokens';

// Anciens noms utilisés par les écrans existants (imports depuis '../theme').
// Le nouveau kit importe les tokens ci-dessus directement depuis './tokens'.
export {
  legacyColors as oldColors,
  brand,
  dark,
  legacyRadii as oldRadii,
  legacyShadows as oldShadows,
  legacySpacing as oldSpacing,
  legacyGradients as oldGradients,
  play,
  legacyColors as colors,
  legacyGradients as gradients,
  legacyRadii as radii,
  legacyShadows as shadows,
  legacySpacing as spacing,
  legacyFonts as fonts,
  legacyTypography as typography,
} from './tokens';
