import type { TextStyle, ViewStyle } from 'react-native';

export const colors = {
  navy: '#0A1B3D',
  navyLight: '#1A3A7A',
  navyDeep: '#06122A',
  navyTint: '#E8EDF6',
  navyInk: '#0A1B3D',

  green: '#0BAA4F',
  greenDark: '#067A37',
  greenInk: '#065C2A',
  greenTint: '#EAF7EF',
  greenTint2: '#DDF3E6',
  greenGlow: '#3BE08A',

  yellow: '#FFB400',
  yellowTint: '#FFF4D6',
  yellowInk: '#7A5200',

  bg: '#F5F7FB',
  surface: '#FFFFFF',
  border: '#E1E6EF',

  fieldPrefix: '#F1F4F9',
  track: '#E6ECF5',
  track2: '#DDE3EE',
  muted: '#5B6680',
  subtle: '#8A93A8',
  ink2: '#3C4760',

  disabledBg: '#EEF1F6',
  disabledBorder: '#CBD3E1',

  wrongBg: '#FFF1E6',
  wrong: '#C2410C',
  wrongInk: '#9A3412',

  focusRing: 'rgba(11, 170, 79, 0.12)',
};

export const gradients = {
  hero: [
    'rgba(11,170,79,0.42)',
    'rgba(11,170,79,0)',
    '#1A3A7A',
    '#0A1B3D',
    '#06122A',
  ] as const,
  heroConduite: [
    'rgba(255,180,0,0.28)',
    'rgba(255,180,0,0)',
    '#1A3A7A',
    '#0A1B3D',
    '#06122A',
  ] as const,
  progress: ['#0BAA4F', '#FFB400'] as const,
  sidebar: [
    'rgba(11,170,79,0.28)',
    'rgba(11,170,79,0)',
    '#0F2554',
    '#0A1B3D',
    '#06122A',
  ] as const,
  welcome: [
    'rgba(11,170,79,0.38)',
    'rgba(11,170,79,0)',
    '#16306A',
    '#0A1B3D',
    '#06122A',
  ] as const,
  offers: [
    'rgba(11,170,79,0.40)',
    'rgba(11,170,79,0)',
    '#1A3A7A',
    '#0A1B3D',
    '#06122A',
  ] as const,
  loginAside: ['#001830', '#002818', '#003820'] as const,
  loginShell: ['#F8FAFC', '#F1F5F9'] as const,
  btnPrimary: ['#00C45A', '#009944'] as const,
  btnPrimaryHover: ['#00D566', '#00A348'] as const,
  tabActive: ['#00C45A', '#00A348'] as const,
};

export const glass = {
  bg: 'rgba(255,255,255,0.08)',
  border: 'rgba(255,255,255,0.20)',
  blur: 12,
  highlight: 'rgba(255,255,255,0.12)',
  highlightStrong: 'rgba(255,255,255,0.18)',
};

export const shadows = {
  card: {
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.30,
    shadowRadius: 30,
    elevation: 8,
  },
  hero: {
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 26 },
    shadowOpacity: 0.75,
    shadowRadius: 44,
    elevation: 12,
  },
  button: {
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 18,
    elevation: 4,
  },
  ctaYellow: {
    shadowColor: '#FFB400',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.60,
    shadowRadius: 30,
    elevation: 8,
  },
  ctaNavy: {
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.65,
    shadowRadius: 32,
    elevation: 10,
  },
  tabBar: {
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.60,
    shadowRadius: 40,
    elevation: 12,
  },
  adminCard: {
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 30,
    elevation: 6,
  },
  adminHero: {
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.80,
    shadowRadius: 40,
    elevation: 10,
  },
  login: {
    shadowColor: '#001030',
    shadowOffset: { width: 0, height: 28 },
    shadowOpacity: 0.28,
    shadowRadius: 64,
    elevation: 16,
  },
  loginBtn: {
    shadowColor: '#00B050',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.70,
    shadowRadius: 24,
    elevation: 6,
  },
  loginBtnHover: {
    shadowColor: '#00B050',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.80,
    shadowRadius: 28,
    elevation: 8,
  },
};

export const typography = {
  fontDisplay: 'Sora',
  fontBody: 'Plus Jakarta Sans',

  fontWeights: {
    medium: '500' as const,
    semiBold: '600' as const,
    bold: '700' as const,
    extraBold: '800' as const,
  },

  letterSpacing: {
    title: -0.02,
    heroNumber: -0.04,
    kicker: 0.06,
    section: -0.03,
    kpi: -0.03,
    tabLabel: 0.02,
  },

  sizes: {
    heroNumber: 56,
    h1Screen: 26,
    h1Welcome: 30,
    h1Login: 30,
    section: 18,
    cardTitle: 16,
    cardTitleSm: 15,
    body: 14.5,
    bodySm: 13.5,
    meta: 12.5,
    metaSm: 12,
    tabLabel: 10.5,
    chip: 12,
    chipSm: 11.5,
    input: 15,
    kpiValue: 36,
    kpiUnit: 16,
    sidebarTitle: 17,
    sidebarSubtitle: 12,
    navItem: 14,
    navGroup: 11,
    userName: 13.5,
    userEmail: 12,
    tableHeader: 11.5,
    tableCell: 13.5,
    btnNew: 14,
    search: 14,
    date: 13.5,
    legend: 13,
    manageBtn: 13.5,
  },

  lineHeights: {
    heroNumber: 0.95,
    tight: 1.1,
    normal: 1.45,
    relaxed: 1.55,
  },
};

export const radii = {
  hero: 32,
  heroCodeConduite: 28,
  card: 24,
  cardLg: 26,
  tile: 22,
  field: 18,
  pill: 9999,
  logoTileSm: 15,
  logoTileLg: 48,
  tabBar: 36,
  tabPill: 28,
  notchedTab: { topLeft: 20, topRight: 20, bottomLeft: 0, bottomRight: 0 },
  notchedBody: { topLeft: 0, topRight: 24, bottomLeft: 24, bottomRight: 24 },
  progressRing: 105,
  scoreBar: 10,
  optionBtn: 22,
  optionLetter: 20,
  dayPill: 22,
  slotBtn: 24,
  monitorChip: 26,
  monitorAvatar: 20,
  search: 26,
  planCard: 24,
  radio: 12,
  radioDot: 5,
  segmentedTrack: 21,
  segmentedBtn: 21,
  iconBtn: 23,
  bellBadge: 5,
  badge: 15,
  badgeSm: 14,
  badgeXs: 11,
  kpi: 26,
  kpiBadge: 14,
  chartBarTop: { topLeft: 8, topRight: 8, bottomLeft: 3, bottomRight: 3 },
  chartBarBottom: { topLeft: 3, topRight: 3, bottomLeft: 8, bottomRight: 8 },
  donut: 46,
  tableHeader: 14,
  tableRow: 13,
  statusBadge: 13,
  paymentIcon: 13,
  userAvatar: 20,
  loginShell: 32,
  loginInput: 14,
  loginBtn: 14,
  portalTab: 14,
};

export const spacing = {
  screenTop: 56,
  screenHorizontal: 20,
  blockGap: 14,
  blockGapLg: 20,
  gridGap: 10,
  gridGapSm: 8,
  gridGapLg: 12,
  sectionGap: 18,
  tabBarBottom: 22,
  tabBarHorizontal: 16,
  contentBottomPadding: 120,
  cardPadding: 18,
  cardPaddingLg: 20,
  cardPaddingXl: 22,
  heroPadding: 20,
  glassAction: 10,
  notchedTab: 40,
  progressRing: 270,
  miniCardPadding: 10,
  chipPadding: 12,
  chipHeight: 30,
  chipHeightSm: 28,
  optionBtnHeight: 58,
  optionLetter: 40,
  dayPill: 72,
  slotBtn: 48,
  monitorChip: 52,
  monitorAvatar: 40,
  planCard: 76,
  searchHeight: 52,
  textFieldHeight: 56,
  segmentedHeight: 52,
  segmentedPadding: 5,
  buttonHeight: 58,
  buttonHeightSm: 56,
  buttonHeightLg: 60,
  iconBtn: 46,
  logoTile: 46,
  logoTileLg: 196,
  tabBarHeight: 72,
  tabPill: 56,
  tabPillWidth: 64,
};

export const halos = {
  sizes: {
    sm: 240,
    md: 260,
    lg: 280,
    xl: 300,
  },
  blur: {
    sm: 50,
    md: 55,
    lg: 60,
  },
  greenOpacity: {
    sm: 0.10,
    md: 0.12,
    lg: 0.14,
  },
  yellowOpacity: 0.16,
};

export const transitions = {
  fast: 150,
  normal: 200,
  slow: 300,
};

export const zIndex = {
  tabBar: 100,
  modal: 200,
  toast: 300,
  tooltip: 400,
};

export const layout = {
  sidebarWidth: 272,
  maxContentWidth: 480,
  tabBarHeight: 72,
  tabBarHorizontalInset: 16,
  tabBarBottomInset: 22,
};

export const routePattern = {
  home: require('../assets/route-pattern-home.svg'),
  admin: require('../assets/route-pattern-admin.svg'),
  login: require('../assets/route-pattern-login.svg'),
};

export const fontFamilies = {
  display: {
    500: 'Sora_500Medium',
    600: 'Sora_600SemiBold',
    700: 'Sora_700Bold',
    800: 'Sora_800ExtraBold',
  },
  body: {
    400: 'PlusJakartaSans_400Regular',
    500: 'PlusJakartaSans_500Medium',
    600: 'PlusJakartaSans_600SemiBold',
    700: 'PlusJakartaSans_700Bold',
    800: 'PlusJakartaSans_800ExtraBold',
  },
};

export const textStyles = {
  heroNumber: {
    fontFamily: 'Sora_800ExtraBold',
    fontSize: 56,
    lineHeight: 53,
    letterSpacing: -2.24,
    color: '#FFFFFF',
  },
  h1Screen: {
    fontFamily: 'Sora_700Bold',
    fontSize: 26,
    lineHeight: 32,
    letterSpacing: -0.52,
    color: '#0A1B3D',
  },
  h1Welcome: {
    fontFamily: 'Sora_800ExtraBold',
    fontSize: 32,
    lineHeight: 36,
    letterSpacing: -0.96,
    color: '#0A1B3D',
  },
  h1Login: {
    fontFamily: 'Sora_700Bold',
    fontSize: 30,
    lineHeight: 36,
    letterSpacing: -0.6,
    color: '#0A1B3D',
  },
  section: {
    fontFamily: 'Sora_700Bold',
    fontSize: 18,
    lineHeight: 24,
    letterSpacing: -0.36,
    color: '#0A1B3D',
  },
  cardTitle: {
    fontFamily: 'Sora_700Bold',
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.32,
    color: '#0A1B3D',
  },
  cardTitleSm: {
    fontFamily: 'Sora_700Bold',
    fontSize: 15,
    lineHeight: 21,
    letterSpacing: -0.3,
    color: '#0A1B3D',
  },
  body: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 14.5,
    lineHeight: 22,
    color: '#0A1B3D',
  },
  bodySm: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 13.5,
    lineHeight: 20,
    color: '#0A1B3D',
  },
  meta: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 12.5,
    lineHeight: 18,
    color: '#5B6680',
  },
  metaSm: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 12,
    lineHeight: 16,
    color: '#5B6680',
  },
  tabLabel: {
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 10.5,
    lineHeight: 14,
    letterSpacing: 0.21,
    color: '#FFFFFF',
  },
  chip: {
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.24,
  },
  chipSm: {
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 11.5,
    lineHeight: 15,
    letterSpacing: 0.23,
  },
  input: {
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 15,
    lineHeight: 22,
    color: '#0A1B3D',
  },
  kpiValue: {
    fontFamily: 'Sora_700Bold',
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: -1.08,
    color: '#FFFFFF',
  },
  kpiUnit: {
    fontFamily: 'Sora_700Bold',
    fontSize: 16,
    lineHeight: 22,
    color: '#FFFFFF',
  },
  kpiTrend: {
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    fontSize: 12,
    lineHeight: 16,
  },
  sidebarTitle: {
    fontFamily: 'Sora_800ExtraBold',
    fontSize: 17,
    lineHeight: 22,
    letterSpacing: -0.51,
    color: '#FFFFFF',
  },
  sidebarSubtitle: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 12,
    lineHeight: 16,
    color: 'rgba(255,255,255,0.65)',
  },
  navItem: {
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 14,
    lineHeight: 20,
    color: 'rgba(255,255,255,0.74)',
  },
  navItemActive: {
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  navGroup: {
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 0.88,
    textTransform: 'uppercase' as const,
    color: 'rgba(255,255,255,0.5)',
  },
  userName: {
    fontFamily: 'Sora_700Bold',
    fontSize: 13.5,
    lineHeight: 18,
    color: '#FFFFFF',
  },
  userEmail: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 12,
    lineHeight: 16,
    color: 'rgba(255,255,255,0.65)',
  },
  tableHeader: {
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    fontSize: 11.5,
    lineHeight: 15,
    letterSpacing: 0.46,
    textTransform: 'uppercase' as const,
    color: '#5B6680',
  },
  tableCell: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 13.5,
    lineHeight: 20,
    color: '#0A1B3D',
  },
  btnNew: {
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    fontSize: 14,
    lineHeight: 20,
    color: '#0A1B3D',
  },
  search: {
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 14,
    lineHeight: 20,
    color: '#0A1B3D',
  },
  date: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 13.5,
    lineHeight: 18,
    color: '#5B6680',
  },
  legend: {
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 13,
    lineHeight: 18,
    color: '#5B6680',
  },
  manageBtn: {
    fontFamily: 'PlusJakartaSans_700Bold',
    fontSize: 13.5,
    lineHeight: 18,
    color: '#0A1B3D',
  },
  loginAsideBrand: {
    fontFamily: 'Sora_800ExtraBold',
    fontSize: 34,
    lineHeight: 38,
    letterSpacing: -1.02,
    color: '#FFFFFF',
  },
  loginAsideText: {
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 14.5,
    lineHeight: 22,
    color: 'rgba(255,255,255,0.78)',
  },
  loginPoint: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 13.5,
    lineHeight: 19,
    color: 'rgba(255,255,255,0.88)',
  },
  loginBadge: {
    fontFamily: 'PlusJakartaSans_550Medium',
    fontSize: 13.5,
    lineHeight: 18,
    color: '#5B6680',
  },
  loginPortalTab: {
    fontFamily: 'PlusJakartaSans_650SemiBold',
    fontSize: 14,
    lineHeight: 20,
    color: '#5B6680',
  },
  loginPortalTabActive: {
    fontFamily: 'PlusJakartaSans_650SemiBold',
    fontSize: 14,
    lineHeight: 20,
    color: '#FFFFFF',
  },
  loginFormLabel: {
    fontFamily: 'PlusJakartaSans_650SemiBold',
    fontSize: 13,
    lineHeight: 18,
    color: '#0A1B3D',
  },
  loginFormInput: {
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 14,
    lineHeight: 20,
    color: '#0A1B3D',
  },
  loginHint: {
    fontFamily: 'PlusJakartaSans_500Medium',
    fontSize: 12.5,
    lineHeight: 19,
    color: '#5B6680',
  },
  loginSubmit: {
    fontFamily: 'PlusJakartaSans_800ExtraBold',
    fontSize: 16,
    lineHeight: 22,
    color: '#FFFFFF',
  },
  loginFooterLabel: {
    fontFamily: 'PlusJakartaSans_650SemiBold',
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 0.44,
    textTransform: 'uppercase' as const,
    color: '#5B6680',
  },
  loginTrust: {
    fontFamily: 'PlusJakartaSans_550Medium',
    fontSize: 11.5,
    lineHeight: 16,
    color: '#334155',
  },
  loginSwitch: {
    fontFamily: 'PlusJakartaSans_600SemiBold',
    fontSize: 13,
    lineHeight: 18,
    color: '#5B6680',
  },
};

export const componentStyles = {
  logoTile: {
    width: 46,
    height: 46,
    borderRadius: 15,
    backgroundColor: '#FFFFFF',
    ...shadows.button,
    overflow: 'hidden' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  logoTileLg: {
    width: 196,
    height: 196,
    borderRadius: 48,
    backgroundColor: '#FFFFFF',
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 30 },
    shadowOpacity: 0.35,
    shadowRadius: 60,
    elevation: 10,
    borderWidth: 1,
    borderColor: '#EEF1F6',
    overflow: 'hidden' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  iconBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#FFFFFF',
    ...shadows.button,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  iconBtnBell: {
    position: 'relative' as const,
  },
  bellBadge: {
    position: 'absolute' as const,
    top: -2,
    right: -2,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9999,
    backgroundColor: '#FFB400',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  buttonPrimary: {
    height: 58,
    borderRadius: 29,
    backgroundColor: '#0A1B3D',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    flexDirection: 'row' as const,
    gap: 10,
    ...shadows.ctaNavy,
  },
  buttonAccent: {
    height: 58,
    borderRadius: 29,
    backgroundColor: '#FFB400',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    flexDirection: 'row' as const,
    gap: 10,
    ...shadows.ctaYellow,
  },
  buttonOutline: {
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E1E6EF',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    flexDirection: 'row' as const,
    gap: 10,
  },
  buttonGoogle: {
    height: 56,
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E1E6EF',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    flexDirection: 'row' as const,
    gap: 10,
  },
  buttonSlider: {
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FFB400',
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 22,
    flexDirection: 'row' as const,
    ...shadows.ctaYellow,
  },
  buttonSliderIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#0A1B3D',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  textField: {
    height: 56,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E1E6EF',
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 16,
    gap: 10,
  },
  textFieldFocus: {
    borderColor: '#0BAA4F',
    shadowColor: '#0BAA4F',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 2,
  },
  textFieldPrefix: {
    height: 40,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: '#F1F4F9',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  segmentedControl: {
    height: 52,
    borderRadius: 26,
    backgroundColor: '#E8EDF6',
    flexDirection: 'row' as const,
    padding: 5,
    gap: 4,
  },
  segmentedBtn: {
    flex: 1,
    borderRadius: 21,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingVertical: 10,
  },
  segmentedBtnActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 3,
  },
  heroCard: {
    borderRadius: 32,
    padding: 22,
    ...shadows.hero,
  },
  heroCardCodeConduite: {
    borderRadius: 28,
    padding: 18,
    ...shadows.hero,
  },
  glassAction: {
    height: 76,
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.20)',
    flexDirection: 'column' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
  },
  glassActionAccent: {
    backgroundColor: '#FFB400',
    borderColor: 'transparent',
  },
  notchedCard: {
    borderRadius: 24,
    overflow: 'hidden' as const,
    backgroundColor: '#0A1B3D',
    ...shadows.hero,
  },
  notchedTab: {
    height: 40,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 20,
    gap: 8,
  },
  notchedBody: {
    borderTopLeftRadius: 0,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    padding: 16,
  },
  tabBar: {
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(10,27,61,0.93)',
    paddingHorizontal: 8,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    ...shadows.tabBar,
  },
  tabPill: {
    width: 64,
    height: 56,
    borderRadius: 28,
    flexDirection: 'column' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 3,
  },
  tabPillActive: {
    backgroundColor: '#FFB400',
  },
  tabPillInactive: {
    backgroundColor: 'transparent',
  },
  progressRing: {
    width: 270,
    height: 270,
  },
  progressRingStroke: 24,
  progressRingRadius: 105,
  segmentedProgressQcm: {
    segmentWidth: 6,
    segmentGap: 3,
    height: 6,
    borderRadius: 3,
  },
  segmentedProgressConduite: {
    segmentWidth: 8,
    segmentGap: 4,
    height: 8,
    borderRadius: 4,
  },
  scoreBars: {
    height: 120,
    barCount: 6,
    barBorderRadius: 10,
    maxBarHeight: 100,
  },
  optionBtn: {
    minHeight: 58,
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingVertical: 8,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  optionLetter: {
    width: 40,
    height: 40,
    borderRadius: 20,
    flexShrink: 0,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  planCard: {
    minHeight: 76,
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
    borderWidth: 1.5,
    borderColor: '#E1E6EF',
    backgroundColor: '#FFFFFF',
  },
  planCardSelected: {
    backgroundColor: 'transparent',
    borderColor: '#0A1B3D',
  },
  planRadio: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#CBD3E1',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  planRadioSelected: {
    borderColor: '#FFB400',
  },
  planRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  dayPill: {
    height: 72,
    borderRadius: 22,
    flex: 1,
    flexDirection: 'column' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 4,
  },
  dayPillSelected: {
    backgroundColor: '#0A1B3D',
    borderWidth: 1.5,
    borderColor: '#0A1B3D',
    shadowColor: '#0A1B3D',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.8,
    shadowRadius: 24,
    elevation: 6,
  },
  dayPillUnselected: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E1E6EF',
  },
  slotBtn: {
    height: 48,
    borderRadius: 24,
    flex: 1,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  slotBtnAvailable: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E1E6EF',
  },
  slotBtnSelected: {
    backgroundColor: '#EAF7EF',
    borderWidth: 2,
    borderColor: '#0BAA4F',
  },
  slotBtnUnavailable: {
    backgroundColor: '#EEF1F6',
    borderWidth: 1.5,
    borderStyle: 'dashed' as const,
    borderColor: '#CBD3E1',
  },
  monitorChip: {
    height: 52,
    borderRadius: 26,
    paddingHorizontal: 16,
    paddingVertical: 0,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  monitorChipSelected: {
    backgroundColor: '#0A1B3D',
    borderWidth: 1.5,
    borderColor: '#0A1B3D',
  },
  monitorChipUnselected: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E1E6EF',
  },
  monitorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  searchField: {
    height: 52,
    borderRadius: 26,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#E1E6EF',
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 18,
    gap: 10,
  },
  kpiCard: {
    borderRadius: 26,
    padding: 20,
    flexDirection: 'column' as const,
    gap: 10,
    ...shadows.adminCard,
  },
  kpiCardHero: {
    ...shadows.adminHero,
  },
  kpiLabel: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: 'rgba(255,255,255,0.75)',
  },
  kpiValue: {
    fontFamily: 'Sora_700Bold',
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: -1.08,
    color: '#FFFFFF',
  },
  kpiTrend: {
    height: 28,
    paddingHorizontal: 11,
    borderRadius: 14,
    alignSelf: 'flex-start' as const,
    alignItems: 'center' as const,
    flexDirection: 'row' as const,
    fontSize: 12,
    fontWeight: '800' as const,
  },
  chartCard: {
    borderRadius: 26,
    padding: 22,
    backgroundColor: '#FFFFFF',
    ...shadows.adminCard,
    flexDirection: 'column' as const,
    gap: 16,
  },
  chartTitle: {
    fontFamily: 'Sora_700Bold',
    fontSize: 17,
    lineHeight: 24,
    color: '#0A1B3D',
  },
  chartBars: {
    height: 210,
    flexDirection: 'row' as const,
    alignItems: 'flex-end' as const,
    gap: 18,
    paddingTop: 8,
    flex: 1,
  },
  chartBarGroup: {
    flex: 1,
    flexDirection: 'column' as const,
    alignItems: 'center' as const,
    gap: 3,
  },
  chartBarSegment: {
    width: '100%',
  },
  chartBarLabel: {
    fontSize: 11.5,
    fontWeight: '700' as const,
    color: '#5B6680',
  },
  donutCard: {
    borderRadius: 26,
    padding: 22,
    backgroundColor: '#FFFFFF',
    ...shadows.adminCard,
    flexDirection: 'column' as const,
    gap: 14,
  },
  donutSvg: {
    width: 140,
    height: 140,
  },
  donutLegend: {
    flexDirection: 'column' as const,
    gap: 10,
    fontSize: 13,
    fontWeight: '700' as const,
  },
  donutLegendItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  donutLegendDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  tableCard: {
    borderRadius: 26,
    paddingHorizontal: 22,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    ...shadows.adminCard,
    flexDirection: 'column' as const,
    gap: 10,
  },
  tableHeaderRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
  },
  tableColHeader: {
    flexDirection: 'row' as const,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#F5F7FB',
    borderRadius: 14,
    gap: 12,
  },
  tableRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 12,
  },
  learnerCell: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
  },
  learnerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E8EDF6',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  statusBadge: {
    height: 26,
    paddingHorizontal: 10,
    borderRadius: 13,
    alignSelf: 'flex-start' as const,
    alignItems: 'center' as const,
    fontSize: 11.5,
    fontWeight: '800' as const,
  },
  statusBadgeConfirmed: {
    backgroundColor: '#EAF7EF',
    color: '#067A37',
  },
  statusBadgePending: {
    backgroundColor: '#FFF4D6',
    color: '#7A5200',
  },
  paymentsCard: {
    borderRadius: 26,
    paddingHorizontal: 22,
    paddingVertical: 20,
    backgroundColor: '#FFFFFF',
    ...shadows.adminCard,
    flexDirection: 'column' as const,
    gap: 12,
  },
  paymentItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 12,
  },
  paymentIcon: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  paymentIconYellow: {
    backgroundColor: '#FFF4D6',
  },
  paymentIconGreen: {
    backgroundColor: '#EAF7EF',
  },
  paymentIconNavy: {
    backgroundColor: '#E8EDF6',
  },
  paymentInfo: {
    flex: 1,
    flexDirection: 'column' as const,
    gap: 1,
  },
  paymentName: {
    fontSize: 13.5,
    fontWeight: '700' as const,
    color: '#0A1B3D',
  },
  paymentDetail: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: '#5B6680',
  },
  paymentAmount: {
    fontFamily: 'Sora_700Bold',
    fontSize: 14,
    lineHeight: 18,
    color: '#0A1B3D',
  },
};

export type Colors = typeof colors;
export type Gradients = typeof gradients;
export type Glass = typeof glass;
export type Shadows = typeof shadows;
export type Typography = typeof typography;
export type Radii = typeof radii;
export type Spacing = typeof spacing;
export type Halos = typeof halos;
export type Transitions = typeof transitions;
export type ZIndex = typeof zIndex;
export type Layout = typeof layout;
export type FontFamilies = typeof fontFamilies;
export type TextStyles = typeof textStyles;
export type ComponentStyles = typeof componentStyles;

export const theme = {
  colors,
  gradients,
  glass,
  shadows,
  typography,
  radii,
  spacing,
  halos,
  transitions,
  zIndex,
  layout,
  fontFamilies,
  textStyles,
  componentStyles,
  routePattern,
} as const;

export type Theme = typeof theme;

/* =====================================================================
 * Compatibilité ascendante — anciens noms utilisés par les écrans
 * existants (imports depuis '../theme'). Le nouveau kit importe les
 * tokens ci-dessus directement depuis './tokens'.
 * À supprimer au fur et à mesure de la migration des écrans.
 * ===================================================================== */

export const legacyColors = {
  primary: '#1e40af',
  primaryDark: '#1e3a8a',
  primaryLight: '#3b82f6',
  accent: '#f59e0b',
  success: '#16a34a',
  error: '#dc2626',
  bg: '#f8f9fc',
  surface: '#ffffff',
  text: '#0f172a',
  textMuted: '#64748b',
  border: '#e2e8f0',
  signinAccent: '#00B050',
  white: '#ffffff',
  introBg: '#F4F7FB',
  overlay: 'rgba(0,16,48,0.4)',
} as const;

export const legacyFonts = {
  heading: 'PlayfairDisplay',
  headingBold: 'PlayfairDisplay_700Bold',
  body: 'Inter_400Regular',
  bodyMedium: 'Inter_500Medium',
  bodySemiBold: 'Inter_600SemiBold',
  bodyBold: 'Inter_700Bold',
  display: 'Poppins_600SemiBold',
  displayBold: 'Poppins_700Bold',
  displayExtraBold: 'Poppins_800ExtraBold',
} as const;

export const legacyTypography: Record<string, TextStyle> = {
  h1: { fontFamily: legacyFonts.headingBold, fontSize: 32, lineHeight: 40, letterSpacing: -0.5 },
  h2: { fontFamily: legacyFonts.headingBold, fontSize: 26, lineHeight: 34, letterSpacing: -0.3 },
  h3: { fontFamily: legacyFonts.headingBold, fontSize: 22, lineHeight: 30 },
  h4: { fontFamily: legacyFonts.headingBold, fontSize: 18, lineHeight: 26, letterSpacing: -0.2 },
  subtitle: { fontFamily: legacyFonts.bodySemiBold, fontSize: 15, lineHeight: 22, letterSpacing: 0.1 },
  body: { fontFamily: legacyFonts.body, fontSize: 15, lineHeight: 24 },
  bodySmall: { fontFamily: legacyFonts.body, fontSize: 13, lineHeight: 20 },
  caption: { fontFamily: legacyFonts.bodyMedium, fontSize: 12, lineHeight: 16, letterSpacing: 0.3 },
  label: { fontFamily: legacyFonts.bodySemiBold, fontSize: 13, lineHeight: 18, letterSpacing: 0.5, textTransform: 'uppercase' as const },
  button: { fontFamily: legacyFonts.bodyBold, fontSize: 15, lineHeight: 20, letterSpacing: 0.3 },
  buttonSmall: { fontFamily: legacyFonts.bodySemiBold, fontSize: 13, lineHeight: 18, letterSpacing: 0.2 },
};

export const brand = {
  green: '#00B050',
  gold: '#FFC000',
  navy: '#001030',
  navyMuted: '#3d5a73',
  greenLight: '#e8f8ef',
  goldLight: '#fff8e6',
  greenPale: '#f0fdf4',
  navyPale: '#f1f3f6',
} as const;

export const dark = {
  bg: '#F6F8FC',
  surface: 'rgba(255,255,255,0.92)',
  surfaceRaised: '#EEF2F7',
  border: 'rgba(0,16,48,0.08)',
  textPrimary: '#001030',
  textMuted: '#3d5a73',
  green: '#00B050',
  greenSoft: 'rgba(0,176,80,0.10)',
  coral: '#E85D3B',
  coralSoft: 'rgba(232,93,59,0.10)',
} as const;

export const legacyRadii = { xs: 6, sm: 10, md: 14, lg: 20, xl: 28, pill: 999 } as const;

export const legacyShadows = {
  sm: { shadowColor: '#001030', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 10, elevation: 2 },
  md: { shadowColor: '#001030', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.08, shadowRadius: 18, elevation: 4 },
  lg: { shadowColor: '#001030', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.10, shadowRadius: 28, elevation: 6 },
  card: { shadowColor: '#001030', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.09, shadowRadius: 22, elevation: 5 },
  premium: { shadowColor: '#001030', shadowOffset: { width: 0, height: 10 }, shadowOpacity: 0.10, shadowRadius: 24, elevation: 6 },
} as const;

export const legacySpacing = { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32, xxxl: 48 } as const;

export const legacyGradients = {
  green: ['#00D566', '#00A344'] as const,
  greenDeep: ['#00B050', '#007A38'] as const,
  gold: ['#FFD84D', '#FFB300'] as const,
  navy: ['#16264a', '#0a1530'] as const,
  sky: ['#60C6FF', '#2E93E6'] as const,
  violet: ['#B98BFF', '#8B5CF6'] as const,
  hero: ['#0f1729', '#1a2d47', '#1e3a5f'] as const,
} as const;

export const play = {
  streak: '#FF7A1A',
  streakLight: '#FFF1E6',
  xp: '#FFC000',
  xpLight: '#FFF8E6',
  celebrate: '#8B5CF6',
  celebrateLight: '#F3ECFF',
  sky: '#2E93E6',
  skyLight: '#EAF6FF',
} as const;